
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;





/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author handsomedad
 */
public class CourseSchedulerGUI extends javax.swing.JFrame {

    /**
     * Creates new form CourseSchedulerGUI
     */
    
    private String CurrentSemester;
    private String status;
    private String CurrentStudent;
    
    public CourseSchedulerGUI() {
        initComponents();
        rebuildSemesterComboBoxes();
        rebuildCourseComboBoxes();
        rebuildStudentComboBoxes();
        rebuildStudentCourseComboBox();
    }
    
    public void rebuildSemesterComboBoxes(){
        ArrayList<String> semesters = SemesterQueries.getSemesterList();
        ChangeSemesterCombobox.setModel(new javax.swing.DefaultComboBoxModel(semesters.toArray()));
        if (semesters.size() > 0)
        {
            CurrentSemesterLabel.setText(semesters.get(0));
            CurrentSemester = semesters.get(0);
        }
        else
        {
            CurrentSemesterLabel.setText("None, add a semester.");
            CurrentSemester = "None";
        }
    }
    
    public void rebuildCourseComboBoxes(){
        ArrayList<String> courses = CourseQueries.getAllCourseCodes(CurrentSemester);
        SelectCourseCombobox.setModel(new javax.swing.DefaultComboBoxModel(courses.toArray()));
        DisplayStudentListSelectCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel(courses.toArray()));
        DropCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel(courses.toArray()));
    }
    
    public void rebuildStudentComboBoxes(){
        ArrayList<StudentEntry> students = StudentQueries.getAllStudents();
        ArrayList<String> student_name = new ArrayList<>();
        for (StudentEntry element : students){
            student_name.add(element.getFirstName() + " " + element.getLastName() + " " + element.getStudentID());
        }
        DropStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel(student_name.toArray()));
        CurrentStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel(student_name.toArray()));
        if (student_name.size() > 0)
        {
            CurrentStudentStatusLabel.setText(student_name.get(0));
            CurrentStudent = student_name.get(0);
        }
        else
        {
            CurrentStudentStatusLabel.setText("None, add a student.");
            CurrentStudent = "None";
        }
    }   
    
    public void rebuildStudentCourseComboBox(){
        if (CurrentStudentComboBox.getSelectedIndex() != -1){
                    ArrayList<StudentEntry> student = StudentQueries.getAllStudents();
        String studentID = student.get(CurrentStudentComboBox.getSelectedIndex()).getStudentID();
        ArrayList<ScheduleEntry> schedule = ScheduleQueries.getScheduleByStudent(CurrentSemester,studentID);
        ArrayList<String> coursecode = new ArrayList<>();
        for (ScheduleEntry element : schedule){
            coursecode.add(element.getCourseCode());
        }
        DropCourseSelecteCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel(coursecode.toArray()));
        }

       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CurrentSemesterLabel = new javax.swing.JLabel();
        ChangeSemesterCombobox = new javax.swing.JComboBox<>();
        ChangeSemesterButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        addSemesterTextField = new javax.swing.JTextField();
        AddSemesterSummitButton = new javax.swing.JButton();
        AddSemesterStatusLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        StudentIDTextField = new javax.swing.JTextField();
        FirstNameTextField = new javax.swing.JTextField();
        LastNameTextField = new javax.swing.JTextField();
        AddStudentSummitButton = new javax.swing.JButton();
        AddStudentStatusLabel = new javax.swing.JLabel();
        Jpanel100 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CourseCodeTextFiled = new javax.swing.JTextField();
        CourseDescriptionTextField = new javax.swing.JTextField();
        SeatsSpinner = new javax.swing.JSpinner();
        AddCourseSummitButton = new javax.swing.JButton();
        AddCourseStatusLabel = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        DisplayStudentListSelectCourseComboBox = new javax.swing.JComboBox<>();
        DisplayStudentListDisplayButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ScheduledStudentsTable = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        WaitlistStudentsTable = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        DropStudentComboBox = new javax.swing.JComboBox<>();
        DropStudentButton = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        DropStudentTextArea = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        DropCourseComboBox = new javax.swing.JComboBox<>();
        AdminDropCourseButton = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        AdminDropCourseTextArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayCoursesTable = new javax.swing.JTable();
        DisplayCoursesDisplayButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ScheduleCourseDisplayLabel = new javax.swing.JLabel();
        SelectCourseCombobox = new javax.swing.JComboBox<>();
        ScheduleCourseSummitButton = new javax.swing.JButton();
        ScheduleCoursesSattusLabel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        DisplayScheduleTable = new javax.swing.JTable();
        DisplayScheduleDisplayButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        DropCourseSelecteCourseComboBox = new javax.swing.JComboBox<>();
        UserDropCourseButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        UserDropCourseTextArea = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        CurrentStudentStatusLabel = new javax.swing.JLabel();
        CurrentStudentComboBox = new javax.swing.JComboBox<>();
        ChangeCurrentStudentButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Course Scheduler");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setText("Current Semester:");

        CurrentSemesterLabel.setText("None");

        ChangeSemesterCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ChangeSemesterButton.setText("Change Semester");
        ChangeSemesterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeSemesterButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Semester Name:");

        addSemesterTextField.setColumns(15);

        AddSemesterSummitButton.setText("Summit");
        AddSemesterSummitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSemesterSummitButtonActionPerformed(evt);
            }
        });

        AddSemesterStatusLabel.setText("               ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addSemesterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(AddSemesterSummitButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(AddSemesterStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(341, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addSemesterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddSemesterSummitButton))
                .addGap(57, 57, 57)
                .addComponent(AddSemesterStatusLabel)
                .addContainerGap(327, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Add Semester", jPanel3);

        jLabel8.setText("Student ID:");

        jLabel9.setText("First Name:");

        jLabel10.setText("Last Name:");

        StudentIDTextField.setColumns(10);

        FirstNameTextField.setColumns(20);

        LastNameTextField.setColumns(20);

        AddStudentSummitButton.setText("Summit");
        AddStudentSummitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentSummitButtonActionPerformed(evt);
            }
        });

        AddStudentStatusLabel.setText("            ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 363, Short.MAX_VALUE)
                .addComponent(AddStudentSummitButton)
                .addGap(339, 339, 339))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(StudentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AddStudentStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(StudentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(AddStudentStatusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(AddStudentSummitButton)
                .addGap(67, 67, 67))
        );

        jTabbedPane2.addTab("Add Student", jPanel5);

        jLabel5.setText("Course Code:");

        jLabel6.setText("Course Description:");

        jLabel7.setText("Seats:");

        CourseCodeTextFiled.setColumns(20);

        CourseDescriptionTextField.setColumns(50);

        AddCourseSummitButton.setText("Summit");
        AddCourseSummitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCourseSummitButtonActionPerformed(evt);
            }
        });

        AddCourseStatusLabel.setText("           ");

        javax.swing.GroupLayout Jpanel100Layout = new javax.swing.GroupLayout(Jpanel100);
        Jpanel100.setLayout(Jpanel100Layout);
        Jpanel100Layout.setHorizontalGroup(
            Jpanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel100Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddCourseSummitButton)
                .addGap(348, 348, 348))
            .addGroup(Jpanel100Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(Jpanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddCourseStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Jpanel100Layout.createSequentialGroup()
                        .addGroup(Jpanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Jpanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6))
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)
                        .addGroup(Jpanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CourseCodeTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CourseDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SeatsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Jpanel100Layout.setVerticalGroup(
            Jpanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel100Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(Jpanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CourseCodeTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(Jpanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CourseDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(Jpanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(SeatsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(AddCourseStatusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(AddCourseSummitButton)
                .addGap(63, 63, 63))
        );

        jTabbedPane2.addTab("Add Course", Jpanel100);

        jLabel15.setText("Select Course:");

        DisplayStudentListSelectCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        DisplayStudentListDisplayButton.setText("Display");
        DisplayStudentListDisplayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayStudentListDisplayButtonActionPerformed(evt);
            }
        });

        jLabel16.setText("Scheduled Students:");

        ScheduledStudentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Student ID"
            }
        ));
        jScrollPane5.setViewportView(ScheduledStudentsTable);

        jLabel17.setText("Waitlist Students:");

        WaitlistStudentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Student ID"
            }
        ));
        jScrollPane6.setViewportView(WaitlistStudentsTable);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DisplayStudentListSelectCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)
                                .addComponent(DisplayStudentListDisplayButton))
                            .addComponent(jLabel16))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(DisplayStudentListSelectCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisplayStudentListDisplayButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Display Course List of Students", jPanel9);

        jLabel18.setText("Select Student to Drop:");

        DropStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        DropStudentButton.setText("Drop Student");
        DropStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropStudentButtonActionPerformed(evt);
            }
        });

        DropStudentTextArea.setColumns(20);
        DropStudentTextArea.setRows(5);
        jScrollPane7.setViewportView(DropStudentTextArea);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(DropStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(DropStudentButton)
                .addContainerGap(280, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(DropStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DropStudentButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Drop Student", jPanel10);

        jLabel19.setText("Selecte Course to Drop:");

        DropCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AdminDropCourseButton.setText("Drop Course");
        AdminDropCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminDropCourseButtonActionPerformed(evt);
            }
        });

        AdminDropCourseTextArea.setColumns(20);
        AdminDropCourseTextArea.setRows(5);
        jScrollPane8.setViewportView(AdminDropCourseTextArea);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(DropCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(AdminDropCourseButton)
                .addContainerGap(285, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(DropCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminDropCourseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Drop Course", jPanel11);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Admin", jPanel1);

        DisplayCoursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course code", "Description", "Seats"
            }
        ));
        jScrollPane1.setViewportView(DisplayCoursesTable);

        DisplayCoursesDisplayButton.setText("Display");
        DisplayCoursesDisplayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayCoursesDisplayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(DisplayCoursesDisplayButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DisplayCoursesDisplayButton)
                .addGap(18, 18, 18))
        );

        jTabbedPane3.addTab("Display Courses", jPanel6);

        jLabel11.setText("Select Course:");

        ScheduleCourseDisplayLabel.setText("             ");

        SelectCourseCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ScheduleCourseSummitButton.setText("Summit");
        ScheduleCourseSummitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScheduleCourseSummitButtonActionPerformed(evt);
            }
        });

        ScheduleCoursesSattusLabel.setText("              ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ScheduleCourseDisplayLabel)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(48, 48, 48)
                                .addComponent(SelectCourseCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(182, 182, 182)
                        .addComponent(ScheduleCourseSummitButton))
                    .addComponent(ScheduleCoursesSattusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ScheduleCourseSummitButton)
                    .addComponent(SelectCourseCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(94, 94, 94)
                .addComponent(ScheduleCoursesSattusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(ScheduleCourseDisplayLabel)
                .addGap(103, 103, 103))
        );

        jTabbedPane3.addTab("Schedule Courses", jPanel7);

        DisplayScheduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Course Code", "Status"
            }
        ));
        jScrollPane3.setViewportView(DisplayScheduleTable);

        DisplayScheduleDisplayButton.setText("Display");
        DisplayScheduleDisplayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayScheduleDisplayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(DisplayScheduleDisplayButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(DisplayScheduleDisplayButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jTabbedPane3.addTab("Display Schedule", jPanel8);

        jLabel3.setText("Select Course:");

        DropCourseSelecteCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        UserDropCourseButton.setText("Drop Course");
        UserDropCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserDropCourseButtonActionPerformed(evt);
            }
        });

        UserDropCourseTextArea.setColumns(20);
        UserDropCourseTextArea.setRows(5);
        jScrollPane4.setViewportView(UserDropCourseTextArea);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(22, 22, 22)
                                .addComponent(DropCourseSelecteCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(UserDropCourseButton)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DropCourseSelecteCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(UserDropCourseButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Drop Course", jPanel4);

        jLabel20.setText("Current Student:");

        CurrentStudentStatusLabel.setText("None");

        CurrentStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ChangeCurrentStudentButton.setText("Change Student");
        ChangeCurrentStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeCurrentStudentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(CurrentStudentStatusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CurrentStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ChangeCurrentStudentButton)
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(CurrentStudentStatusLabel)
                    .addComponent(CurrentStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChangeCurrentStudentButton))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Student", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(CurrentSemesterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ChangeSemesterCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChangeSemesterButton))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(324, 324, 324))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CurrentSemesterLabel)
                    .addComponent(ChangeSemesterCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChangeSemesterButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddSemesterSummitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSemesterSummitButtonActionPerformed
        // TODO add your handling code here:
        String semester = addSemesterTextField.getText();
        SemesterQueries.addSemester(semester);
        AddSemesterStatusLabel.setText("Semester: " + semester + " has been added.");
        rebuildSemesterComboBoxes();
    }//GEN-LAST:event_AddSemesterSummitButtonActionPerformed

    private void AddCourseSummitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCourseSummitButtonActionPerformed
        // TODO add your handling code here:
        String coursecode = CourseCodeTextFiled.getText();
        String coursedescription = CourseDescriptionTextField.getText();
        int seats = (int)SeatsSpinner.getValue();
        CourseEntry course = new CourseEntry(CurrentSemester, coursecode, coursedescription, seats);
        CourseQueries.addCourse(course);
        AddCourseStatusLabel.setText(coursecode + " has been added.");
        rebuildCourseComboBoxes();
        
    }//GEN-LAST:event_AddCourseSummitButtonActionPerformed

    private void AddStudentSummitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentSummitButtonActionPerformed
        // TODO add your handling code here:
        String studentID = StudentIDTextField.getText();
        String firstname = FirstNameTextField.getText();
        String lastname = LastNameTextField.getText();
        StudentEntry student = new StudentEntry(studentID, firstname, lastname);
        StudentQueries.addStudent(student);
        AddStudentStatusLabel.setText(firstname + " " + lastname + " " + studentID + " has been added.");
        rebuildStudentComboBoxes();
    }//GEN-LAST:event_AddStudentSummitButtonActionPerformed

    private void DisplayCoursesDisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayCoursesDisplayButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<CourseEntry> Course = CourseQueries.getAllCourses(CurrentSemester);
        DefaultTableModel DisplayCoursesTableModel = (DefaultTableModel)DisplayCoursesTable.getModel();
        DisplayCoursesTableModel.setNumRows(0);
        Object[] rowData = new Object[3];
        
        for (CourseEntry course:Course){
            rowData[0] = course.getCourseCode();
            rowData[1] = course.getDescription();
            rowData[2] = course.getSeats();
            DisplayCoursesTableModel.addRow(rowData);
        }
    }//GEN-LAST:event_DisplayCoursesDisplayButtonActionPerformed

    private void ScheduleCourseSummitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScheduleCourseSummitButtonActionPerformed
        // TODO add your handling code here:
        String coursecode = SelectCourseCombobox.getSelectedItem().toString();
        ArrayList<StudentEntry> student = StudentQueries.getAllStudents();
        String studentID = student.get(CurrentStudentComboBox.getSelectedIndex()).getStudentID();
        java.sql.Timestamp currentTimestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
        int courseseats = CourseQueries.getCourseSeats(CurrentSemester, coursecode);
        int students_in_course = ScheduleQueries.getScheduledStudentCount(CurrentSemester, coursecode); 
        if (students_in_course < courseseats){
            status = "Scheduled";
        }
        else{ 
            status = "Waitlisted";
        }
        
        ScheduleEntry schedule = new ScheduleEntry(CurrentSemester, coursecode, studentID, status, currentTimestamp);   
        ScheduleQueries.addScheduleEntry(schedule);
        ScheduleCoursesSattusLabel.setText(CurrentStudent + " is in " + status + " of " + coursecode);
                   
    }//GEN-LAST:event_ScheduleCourseSummitButtonActionPerformed

    private void DisplayScheduleDisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayScheduleDisplayButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<StudentEntry> student = StudentQueries.getAllStudents();
        String studentID = student.get(CurrentStudentComboBox.getSelectedIndex()).getStudentID();
        ArrayList<ScheduleEntry> Schedule = ScheduleQueries.getScheduleByStudent(CurrentSemester, studentID);
        DefaultTableModel DisplayScheduleTableModel = (DefaultTableModel)DisplayScheduleTable.getModel();
        
        Object[] rowData = new Object[2];
        DisplayScheduleTableModel.setNumRows(0);
        
        for(ScheduleEntry schedule:Schedule){
            rowData[0] = schedule.getCourseCode();
            rowData[1] = schedule.getStatus();
            DisplayScheduleTableModel.addRow(rowData);            
        }
    }//GEN-LAST:event_DisplayScheduleDisplayButtonActionPerformed

    private void ChangeSemesterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeSemesterButtonActionPerformed
        // TODO add your handling code here:
        String semester = ChangeSemesterCombobox.getSelectedItem().toString();
        CurrentSemesterLabel.setText(semester);
        CurrentSemester = semester;
        rebuildCourseComboBoxes();
    }//GEN-LAST:event_ChangeSemesterButtonActionPerformed

    private void UserDropCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserDropCourseButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<StudentEntry> student = StudentQueries.getAllStudents();
        String studentID = student.get(CurrentStudentComboBox.getSelectedIndex()).getStudentID();
        String coursecode = DropCourseSelecteCourseComboBox.getSelectedItem().toString();
        
        UserDropCourseTextArea.setText(CurrentStudent + " has been dropped from " + coursecode);
        
        ArrayList<ScheduleEntry> schedule_list = ScheduleQueries.getScheduleByStudent(CurrentSemester, studentID);
        String Status = new String();
        for (ScheduleEntry schedule : schedule_list){
            if (coursecode.equals(schedule.getCourseCode())){
                Status = schedule.getStatus();
            }
        }
        ArrayList<ScheduleEntry> waitlisted_student = ScheduleQueries.getWaitlistedStudentsByCourse(CurrentSemester, coursecode);
        if (Status.equals("Scheduled") && waitlisted_student.size() != 0){
            ScheduleQueries.updateScheduleEntry(waitlisted_student.get(0));
            String studentID_waitlist = waitlisted_student.get(0).getStudentID();
            StudentEntry student_waitlist = StudentQueries.getStudent(studentID_waitlist);
            UserDropCourseTextArea.setText(CurrentStudent + " has been dropped from " + coursecode + "\n" + 
                    student_waitlist.getFirstName() + " " + student_waitlist.getLastName() + "has been scheduled into " + coursecode);
        }
        ScheduleQueries.dropStudentScheduleByCourse(CurrentSemester, studentID, coursecode);
        rebuildStudentCourseComboBox();
        
        
    }//GEN-LAST:event_UserDropCourseButtonActionPerformed

    private void DisplayStudentListDisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayStudentListDisplayButtonActionPerformed
        // TODO add your handling code here:
        String CourseCode = DisplayStudentListSelectCourseComboBox.getSelectedItem().toString();
        ArrayList<ScheduleEntry> Scheduled_Student = ScheduleQueries.getScheduledStudentsByCourse(CurrentSemester, CourseCode);
        ArrayList<ScheduleEntry> Waitlisted_Student = ScheduleQueries.getWaitlistedStudentsByCourse(CurrentSemester, CourseCode);
        ArrayList<StudentEntry> scheduled_student = new ArrayList<>();
        ArrayList<StudentEntry> waitlisted_student = new ArrayList<>();
        
        for (ScheduleEntry element_S : Scheduled_Student){
            String studentID_1 = element_S.getStudentID();
            StudentEntry student_S = StudentQueries.getStudent(studentID_1);
            scheduled_student.add(student_S);
        }
        for (ScheduleEntry element_W : Waitlisted_Student){
            String studentID_2 = element_W.getStudentID();
            StudentEntry student_W = StudentQueries.getStudent(studentID_2);
            waitlisted_student.add(student_W);
        }
        
        DefaultTableModel ScheduledStudentsTableModel = (DefaultTableModel)ScheduledStudentsTable.getModel();
        DefaultTableModel WaitlistStudentsTableModel = (DefaultTableModel)WaitlistStudentsTable.getModel();
        Object[] rowData = new Object[3];
        ScheduledStudentsTableModel.setNumRows(0);
        WaitlistStudentsTableModel.setNumRows(0);
        
        for(StudentEntry student1:scheduled_student){
            rowData[0] = student1.getFirstName();
            rowData[1] = student1.getLastName();
            rowData[2] = student1.getStudentID();
            ScheduledStudentsTableModel.addRow(rowData);            
        }
        for(StudentEntry student2:waitlisted_student){
            rowData[0] = student2.getFirstName();
            rowData[1] = student2.getLastName();
            rowData[2] = student2.getStudentID();
            WaitlistStudentsTableModel.addRow(rowData);            
        }
        
        
        
    }//GEN-LAST:event_DisplayStudentListDisplayButtonActionPerformed

    private void DropStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropStudentButtonActionPerformed
        // TODO add your handling code here:
        String selected_student = DropStudentComboBox.getSelectedItem().toString();
        ArrayList<StudentEntry> student = StudentQueries.getAllStudents();
        String studentID = student.get(DropStudentComboBox.getSelectedIndex()).getStudentID();
        ArrayList<String> semester = SemesterQueries.getSemesterList();
        String message = new String(); 
        for (String element : semester){
            message = message + String.format("\n\nFor Semester: %s", element);
            ArrayList<ScheduleEntry> schedule = ScheduleQueries.getScheduleByStudent(element, studentID);
            
            if (schedule.size() == 0){
                message = message + String.format("\n%s does not schedule any course in %s",selected_student,element);
            }
            else{
                for (ScheduleEntry schedule_entry : schedule){
                    String coursecode = schedule_entry.getCourseCode();
                    message = message + String.format("\n%s has been dropped from %s", selected_student, coursecode);
                    
                    ArrayList<ScheduleEntry> waitlist_student = ScheduleQueries.getWaitlistedStudentsByCourse(element, coursecode);
                    if (schedule_entry.getStatus().equals("Scheduled") && waitlist_student.size() != 0){
                        ScheduleQueries.updateScheduleEntry(waitlist_student.get(0));
                        String studentID_waitlist = waitlist_student.get(0).getStudentID();
                        StudentEntry student_waitlist = StudentQueries.getStudent(studentID_waitlist);
                        message = message + String.format("\n%s %s %s has been scheduled into %s",student_waitlist.getFirstName(),
                                student_waitlist.getLastName(),student_waitlist.getStudentID(),schedule_entry.getCourseCode());  
                    }
                }
            }
        }
        DropStudentTextArea.setText(selected_student + " has been dropped from the list of students." + message);
        StudentQueries.dropStudent(studentID);
        ScheduleQueries.dropScheduleByStudent(studentID);
        rebuildStudentComboBoxes();
        
        
        
    }//GEN-LAST:event_DropStudentButtonActionPerformed

    private void AdminDropCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminDropCourseButtonActionPerformed
        // TODO add your handling code here:
        String coursecode = DropCourseComboBox.getSelectedItem().toString();
        ArrayList<ScheduleEntry> scheduled_student = ScheduleQueries.getScheduledStudentsByCourse(CurrentSemester, coursecode);
        ArrayList<ScheduleEntry> waitlisted_student = ScheduleQueries.getWaitlistedStudentsByCourse(CurrentSemester, coursecode);
        ArrayList<StudentEntry> student_S = new ArrayList<>();
        ArrayList<StudentEntry> student_W = new ArrayList<>();
        for (ScheduleEntry element: scheduled_student){
            StudentEntry student = StudentQueries.getStudent(element.getStudentID());
            student_S.add(student);
        }
        for (ScheduleEntry element : waitlisted_student){
            StudentEntry student = StudentQueries.getStudent(element.getStudentID());
            student_W.add(student);
        }
        
        String schedule_message = new String();
        String waitlist_message = new String();  
        for (StudentEntry element : student_S){
            schedule_message = schedule_message + String.format("%s %s %s\n",element.getFirstName(),element.getLastName(),element.getStudentID());
        }
       
        for (StudentEntry element : student_W){
            waitlist_message = waitlist_message + String.format("%s %s %s\n", element.getFirstName(),element.getLastName(),element.getStudentID());
        }
        
        AdminDropCourseTextArea.setText("Scheduled students dropped from the course:\n" +  schedule_message + "\nWaitlisted students dropped from the course:\n" + waitlist_message );

        CourseQueries.dropCourse(CurrentSemester, coursecode);
        ScheduleQueries.dropScheduleByCourse(CurrentSemester, coursecode);
        
        rebuildCourseComboBoxes();
        rebuildStudentCourseComboBox();
        
        
        
    }//GEN-LAST:event_AdminDropCourseButtonActionPerformed

    private void ChangeCurrentStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeCurrentStudentButtonActionPerformed
        // TODO add your handling code here:
        String student = CurrentStudentComboBox.getSelectedItem().toString();
        CurrentStudentStatusLabel.setText(student);
        CurrentStudent = student;
        rebuildStudentCourseComboBox();
    }//GEN-LAST:event_ChangeCurrentStudentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseSchedulerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddCourseStatusLabel;
    private javax.swing.JButton AddCourseSummitButton;
    private javax.swing.JLabel AddSemesterStatusLabel;
    private javax.swing.JButton AddSemesterSummitButton;
    private javax.swing.JLabel AddStudentStatusLabel;
    private javax.swing.JButton AddStudentSummitButton;
    private javax.swing.JButton AdminDropCourseButton;
    private javax.swing.JTextArea AdminDropCourseTextArea;
    private javax.swing.JButton ChangeCurrentStudentButton;
    private javax.swing.JButton ChangeSemesterButton;
    private javax.swing.JComboBox<String> ChangeSemesterCombobox;
    private javax.swing.JTextField CourseCodeTextFiled;
    private javax.swing.JTextField CourseDescriptionTextField;
    private javax.swing.JLabel CurrentSemesterLabel;
    private javax.swing.JComboBox<String> CurrentStudentComboBox;
    private javax.swing.JLabel CurrentStudentStatusLabel;
    private javax.swing.JButton DisplayCoursesDisplayButton;
    private javax.swing.JTable DisplayCoursesTable;
    private javax.swing.JButton DisplayScheduleDisplayButton;
    private javax.swing.JTable DisplayScheduleTable;
    private javax.swing.JButton DisplayStudentListDisplayButton;
    private javax.swing.JComboBox<String> DisplayStudentListSelectCourseComboBox;
    private javax.swing.JComboBox<String> DropCourseComboBox;
    private javax.swing.JComboBox<String> DropCourseSelecteCourseComboBox;
    private javax.swing.JButton DropStudentButton;
    private javax.swing.JComboBox<String> DropStudentComboBox;
    private javax.swing.JTextArea DropStudentTextArea;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JPanel Jpanel100;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JLabel ScheduleCourseDisplayLabel;
    private javax.swing.JButton ScheduleCourseSummitButton;
    private javax.swing.JLabel ScheduleCoursesSattusLabel;
    private javax.swing.JTable ScheduledStudentsTable;
    private javax.swing.JSpinner SeatsSpinner;
    private javax.swing.JComboBox<String> SelectCourseCombobox;
    private javax.swing.JTextField StudentIDTextField;
    private javax.swing.JButton UserDropCourseButton;
    private javax.swing.JTextArea UserDropCourseTextArea;
    private javax.swing.JTable WaitlistStudentsTable;
    private javax.swing.JTextField addSemesterTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
